# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_install:
  - sudo apt-get -y install libudunits2-dev gdal-bin libgdal1-dev libproj-dev